"""add transcode job types and preview asset types

Revision ID: 530ddff684ef
Revises: 6765fb435cbe
Create Date: 2026-07-20 10:07:59.457595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530ddff684ef'
down_revision: Union[str, Sequence[str], None] = '6765fb435cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated as-is: these are anonymous CHECK
    # constraints (native_enum=False, create_constraint=True), and Alembic's
    # autogenerate only detected a bare column "type change" -- it tried to
    # ADD a same-named constraint without dropping the old one first, which
    # fails immediately (DuplicateObject), and would separately fail against
    # any real existing data (adding a CHECK constraint validates all
    # existing rows, so a still-present 'metadata_and_thumbnail' row would
    # be rejected outright).

    # JobType.METADATA_AND_THUMBNAIL was split into separate METADATA and
    # THUMBNAIL job types; rewrite any existing rows to the new METADATA
    # value first so they satisfy the new constraint below instead of being
    # orphaned by the rename.
    op.execute(
        "UPDATE processing_jobs SET job_type = 'metadata' "
        "WHERE job_type = 'metadata_and_thumbnail'"
    )

    op.drop_constraint('assettype', 'generated_assets', type_='check')
    op.alter_column(
        'generated_assets', 'asset_type',
        existing_type=sa.VARCHAR(length=9),
        type_=sa.VARCHAR(length=13),
        existing_nullable=False,
    )
    op.create_check_constraint(
        'assettype', 'generated_assets',
        "asset_type IN ('thumbnail', 'preview_1080p', 'preview_720p', 'preview_480p')",
    )

    op.drop_constraint('jobtype', 'processing_jobs', type_='check')
    op.alter_column(
        'processing_jobs', 'job_type',
        existing_type=sa.VARCHAR(length=22),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    op.create_check_constraint(
        'jobtype', 'processing_jobs',
        "job_type IN ('metadata', 'thumbnail', 'transcode')",
    )


def downgrade() -> None:
    """Downgrade schema.

    Lossy for job_type: rows using the split METADATA/THUMBNAIL types have
    no single equivalent to merge back into METADATA_AND_THUMBNAIL, so this
    only restores the constraint/column shape, not the original data.
    """
    op.drop_constraint('jobtype', 'processing_jobs', type_='check')
    op.alter_column(
        'processing_jobs', 'job_type',
        existing_type=sa.VARCHAR(length=9),
        type_=sa.VARCHAR(length=22),
        existing_nullable=False,
    )
    op.create_check_constraint(
        'jobtype', 'processing_jobs',
        "job_type IN ('metadata_and_thumbnail')",
    )

    op.drop_constraint('assettype', 'generated_assets', type_='check')
    op.alter_column(
        'generated_assets', 'asset_type',
        existing_type=sa.VARCHAR(length=13),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    op.create_check_constraint(
        'assettype', 'generated_assets',
        "asset_type IN ('thumbnail')",
    )
