"""create initial tables

Revision ID: 6765fb435cbe
Revises: 
Create Date: 2026-07-17 13:06:07.836200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6765fb435cbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_object_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('pending_upload', 'processing', 'completed', 'failed', name='videostatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_object_key')
    )
    op.create_table('generated_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('thumbnail', name='assettype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('video_id', 'asset_type')
    )
    op.create_index(op.f('ix_generated_assets_video_id'), 'generated_assets', ['video_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('metadata_and_thumbnail', name='jobtype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='jobstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'job_type')
    )
    op.create_index(op.f('ix_processing_jobs_video_id'), 'processing_jobs', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_video_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_generated_assets_video_id'), table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_table('videos')
    # ### end Alembic commands ###
